tribes/urls.py
from django.contrib import admin
from django.urls import path
from app.views import index, register, loginF, logoutF, profile, createTribe, joinTribe, tribeDetail, createPlaylist, deletePlaylist, editPlaylist, kickMember, leaveTribe, sendMessage, deleteMessage, playlistDetail, addTrack, upvote, downvote, comment,  deleteTrack, deleteComment

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
   
    path('createtribe/', createTribe, name='createTribe'),
    path('jointribe/<int:tribe_id>', joinTribe, name="joinTribe"),
    path('detailtribe/<int:tribe_id>', tribeDetail, name="tribeDetail"),
    path('createplaylist/<int:tribe_id>', createPlaylist, name="createPlaylist"),
    path('deleteplaylist/<int:tribe_id>/<int:playlist_id>', deletePlaylist, name="deletePlaylist"),
    path('editplaylist/<int:tribe_id>/<int:playlist_id>', editPlaylist, name="editPlaylist"),
    path('kickmember/<int:tribe_id>/<str:member_name>', kickMember, name="kickMember"),
    path('leavetribe/<int:tribe_id>/<str:userName>', leaveTribe, name="leaveTribe"),
    path('sendmessage/<int:tribe_id>', sendMessage, name="sendMessage"),
    path('deletemessage/<int:tribe_id>/<int:message_id>', deleteMessage, name="deleteMessage"),
    path('playlistdetail/<int:tribe_id>/<int:playlist_id>', playlistDetail, name="playlistDetail"),
    path('addTrack/<int:tribe_id>/<int:playlist_id>', addTrack, name="addTrack"),
    path('upvote/<int:tribe_id>/<int:playlist_id>/<int:track_id>/', upvote, name='upvote'),
    path('downvote/<int:tribe_id>/<int:playlist_id>/<int:track_id>/', downvote, name='downvote'),
    path('comment/<int:tribe_id>/<int:playlist_id>/<int:track_id>', comment, name='comment'),
    path('deletetrack/<int:tribe_id>/<int:playlist_id>/<int:track_id>', deleteTrack, name='deleteTrack'),
    path('deletecomment/<int:tribe_id>/<int:playlist_id>/<int:comment_id>', deleteComment, name='deleteComment'),

    path('register/', register, name='register'),
    path('login/', loginF, name='login'),
    path('logout', logoutF, name='logout'),
    path('profile/', profile, name='profile'),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings

class TimeStamped(models.Model):
    created_at = models.DateTimeField(editable=False)
    updated_at = models.DateTimeField(editable=False)

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()

        self.updated_at = timezone.now()
        return super(TimeStamped, self).save(*args, **kwargs)

    class Meta:
        abstract = True

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    profile_pic = models.CharField(max_length=512, default='https://9b16f79ca967fd0708d1-2713572fef44aa49ec323e813b06d2d9.ssl.cf2.rackcdn.com/1140x_a10-7_cTC/NS-WKMAG0730-1595944356.jpg')

class Tribe(models.Model):

    MUSIC_GENRE_TYPE = [
        ('pop', 'pop'),
        ('rock', 'rock'),
        ('folk', 'folk'),
        ('techno', 'techno'),
    ]

    name = models.CharField(max_length=80, unique=True)
    user = models.ForeignKey(User, related_name="user+", on_delete=models.CASCADE)
    music_genre = models.CharField(max_length=50, choices= MUSIC_GENRE_TYPE, default="pop")
    tribe_image = models.CharField(max_length=512, default='https://openai.com/content/images/2020/04/2x-no-mark-1.jpg')
    member = models.ManyToManyField(User, related_name="member+")

    def __str__(self):
        return self.name

class PlayList(TimeStamped):
    tribe = models.ForeignKey(Tribe, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    description = models.TextField(max_length=300)
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Message(TimeStamped):
    tribe = models.ForeignKey(Tribe, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=300)
    profile_pic = models.CharField(max_length=512, default ='https://9b16f79ca967fd0708d1-2713572fef44aa49ec323e813b06d2d9.ssl.cf2.rackcdn.com/1140x_a10-7_cTC/NS-WKMAG0730-1595944356.jpg')

    def __str__(self):
        return self.text

class Track(TimeStamped):
    title = models.CharField(max_length=150)
    playlist = models.ForeignKey(PlayList, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    artist = models.CharField(max_length=150)
    youtube_url = models.CharField(max_length=512)
    duration = models.IntegerField(default=0)
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default = 0)

    def upvote_score(self):
        upvotes = self.vote_set.filter(upvote=True).count()
        return upvotes

    def downvote_score(self):
        downvotes = self.vote_set.filter(upvote=False).count()
        return downvotes

    def vote_score(self):
        upvotes = self.vote_set.filter(upvote=True).count()
        downvotes = self.vote_set.filter(upvote=False).count()
        return upvotes - downvotes
    
    def vote_by(self, user):
        if user.is_authenticated:
            return Vote.objects.filter(user=user, track=self).first()
        else:
            return None

    def __str__(self):
        return self.title

class Vote(TimeStamped):
    track = models.ForeignKey(Track, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    upvote = models.BooleanField(null = False, default=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(name='user_vote', fields=['track', 'user'])
        ]
    
    def __str__(self):
        return f"{self.user.username} voted on {self.track.title}"
    
    def downvote(self):
        return not self.upvote
        
class Comment(TimeStamped):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    track = models.ForeignKey(Track, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    image = models.CharField(max_length=500, default='https://9b16f79ca967fd0708d1-2713572fef44aa49ec323e813b06d2d9.ssl.cf2.rackcdn.com/1140x_a10-7_cTC/NS-WKMAG0730-1595944356.jpg')

    def __str__(self):
        return self.text

app/templates/add_track.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="container">
<h1>Add track</h1>
<form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        {{ form.as_p }} 
        <button type="submit" class="btn btn-primary">Create Track</button>
</form>
</div>
{% endblock %}

app/templates/base.html
{% load static %}
<html>
  <head>
    <title>My Lame Imgur</title>


    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block extrahead %}
    {% endblock %}

    <link rel="stylesheet" href="{% static 'app/css/app.css' %}">
  </head>
  <body>
    <div class="page-header">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">TRIBES</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="#">Hi {{ user.username}}!</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'createTribe' %}">Create tribe</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" href="/admin">Admin Dashboard</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
             </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Sign up</a>
             </li>
             
          {% endif %}
          </ul>
        </div>
      </nav>

    </div>
          {% block content %}
            
          {% endblock %}

  
  </body>
</html>

app/templates/create_playlist.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        {{ form.as_p }} 
        <button type="submit" class="btn btn-primary">Create playlist</button>
</form>
{% endblock %}

app/templates/create_tribe.html
{% extends 'base.html' %}
{% block content %} 
{% load crispy_forms_tags %}
<form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        {{ form.as_p }} 
        <button type="submit" class="btn btn-primary">Create tribe</button>
</form>
{% endblock %}

app/templates/detail_tribe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-8">
            
                <h3>{{ tribe.name }}</h3>
                <!--kreiraj novi playlist-->
                {% if tribe.user == user %}
                    <a href="{% url 'createPlaylist' tribe.id %}">Create Playlist</a>
                {% endif %}
                <!--popis već kreiranih playlista-->
                {% for playlist in playlists %}
                    <div class="mt-4">
                        <h5><a href="{% url 'playlistDetail' tribe.id playlist.id %}">{{ playlist.name }}</a></h5>
                        <p>Description: {{ playlist.description }}</p>
                        <div class="d-flex">
                            {% if tribe.user == user %}
                            <!--izbriši playlist-->
                                <form action="{% url 'deletePlaylist' tribe.id playlist.id%}" method="post"> 
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                                <!--uredi playlist-->
                                <form action="{% url 'editPlaylist' tribe.id playlist.id%}" method="post"> 
                                    {% csrf_token %}
                                    <button type="submit" class="ml-2 btn btn-success">Edit</button>
                                </form>
                            {% endif %}
                        </div> 
                    </div>
                {% endfor %}
                <!--popis članova triba-->
                <h4>MEMBERS:</h4>
                    <div class="card">
                        {{ tribe.user }}
                        {% for member in members %}
                        <div class="d-flex mt-2">
                            <p class="mr-2">{{ member }}
                            {% if member == user %}
                                </p><i class="fa fa-check mt-1" aria-hidden="true">Joined</i ></button>
                                <!--napusti tribe-->
                                <form action="{% url 'leaveTribe' tribe.id user %}" method="post" > 
                                    {% csrf_token %}
                                    <button type="submit" class="ml-2 btn btn-danger"> 
                                    Leave tribe
                                    </button>
                                </form>
                            {% endif %}
                            <!--kikaj člana triba-->
                            {% if tribe.user == user%}
                                <form action="{% url 'kickMember' tribe.id member %}" method="post" > 
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger"> 
                                    Kick
                                    </button>
                                 </form>
                            {% endif %}
                            </div>
                        {% endfor %}
                        
                    </div>
        </div>
    
    <div class="col-sm-4">
    <!--poruke-->
        <h3>Chat</hr>
        <div style="height:500px; overflow:scroll; background:#E0E0E0;">
            {% for message in messages %}
            
                {% if user.is_authenticated and tribe.user == user %}
                    <span style="margin-top:; float:left">
                    <!--izbriši poruku-->
                    <form action="{% url 'deleteMessage' tribe.id message.id%}" method="post" > 
                        {% csrf_token %}
                        <button  style="padding: 0;border: none; background: none; margin-bottom: 40px; color:red;" title="Delete"><i class="fa fa-times" aria-hidden="true"></i></button>
                    </form>
                    </span>
                {% endif %}
                <img src="{{message.profile_pic}}" alt="Avatar" style="float: left; max-width: 50px; width: 100%; margin-right: 20px; border-radius: 50%; height: 50px;"> 
                {% if message.user == tribe.user %}
                    <p  style=" color: orange;">{{message.user}}<span class="iconify" data-icon="fa-solid:crown" data-inline="false" style="margin-bottom: 7px; color: orange;"></span>: {{message.text}} <br><span>{{ message.created_at }}</span></p>
                {% else %}
                    <p  style="">{{message.user}}: {{message.text}} <br><span>{{ message.created_at }}</span></p>
                {% endif %}
                
            {% endfor %}
        </div>
        <!--pošalji poruku-->
        <form role="form" action="{% url 'sendMessage' tribe.id %}" method="post">
            {% csrf_token %}
            {% if tribe.user == user or user in tribe.member.all %}
                <textarea type="text" name="text" maxlength="500" required id="id_text" placeholder="write message..."></textarea> 
                <button type="submit" class="btn btn-primary">Send Message</button>
            {% endif %}
        </form>
    </div>
  </div>
  </div>




{% endblock %}

app/templates/edit_playlist.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        {{ form.as_p }} 
        <button type="submit" class="btn btn-primary">Edit playlist</button>
</form>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
<div class="container">
<!--popis tribeova koja sam ja kreirao-->
    {% if my_tribes %}
        <h3 class="mt-2 text-center">Tribes I created <h3>
        {% for tribe in my_tribes %}
            <div class="mt-2">
                <img class="rounded-circle" src="{{tribe.tribe_image}}" alt="image" style="width:180px; height:180px">
                <a href="{% url 'tribeDetail' tribe.id %}">{{tribe.name}}</a>
            </div>
        
        {% endfor %}
    {% endif %}
    <!--popis tribeova kojima sam se pridružio-->
    {% if member_tribes %}
    <h3 class="mt-2 text-center">Tribes I joined <h3>
        {% for tribe in member_tribes %}
            <div class="mt-2">
                <img class="rounded-circle" src="{{tribe.tribe_image}}" alt="image" style="width:180px; height:180px">
                <a href="{% url 'tribeDetail' tribe.id %}">{{tribe.name}}</a>
            </div>
        {% endfor %}
    {% endif %}

    {% if free_tribes %}
        <h3 class="mt-2 text-center">Tribes I didn`t join <h3>
        <!--popis tribeova koji su slobodni-->
        {% for tribe in free_tribes %}
            <div class="mt-2">
                <img class="rounded-circle" src="{{tribe.tribe_image}}" alt="image" style="width:180px; height:180px">
                <a href="{% url 'tribeDetail' tribe.id %}">{{tribe.name}}</a>
                <!--pridruži se tribe-->
                <form action="{% url 'joinTribe' tribe.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-primary" type="submit">Join</button>
                </form>
            </div>
        {% endfor %}
    {% endif %}
    {% else %}
        {% for tribe in all_tribes %}
            <div class="mt-2">
                <img class="rounded-circle" src="{{tribe.tribe_image}}" alt="image" style="width:180px; height:180px">
                <a href="{% url 'tribeDetail' tribe.id %}">{{tribe.name}}</a>
            </div>
        {% endfor %}
{% endif %}   
{% endblock %}

app/templates/playlist_detail.html
{% extends 'base.html' %}
{% block content %}
    <!--playlist info-->
    <h1 class="mt-4" style="text-align: center;">{{ playlist.name }}<h1>
    <p style="font-size:20px; text-align: center;">{{ playlist.description }}</p>
    <p style="font-size:13px; text-align: center;"> {{ playlist.created_at}}</p>
    <p style="font-size:13px; text-align: center;"> {{ playlist.user }}</p>
    <p style="font-size:25px; text-align: center;"><a href="{% url 'addTrack' tribe.id playlist.id %}">Add track </a></p>
    <hr>
    <!--popis trackova-->
    {% if tracks %}
    {% for track in tracks %}
    <div class="container mt-3" style="border-style: solid; border-color: gray;">
        <p style="font-size:16px; text-align: center;">{{ track.track.artist }}
        <p style="font-size:22px; text-align: center;">{{track.track.title}} </p>
        <p style="font-size:22px; text-align: center;"><a href="{{track.track.youtube_url}}" target="_blank">Play on Youtube</a></p>
        <p style="font-size:16px; text-align: center;">Duration:{{track.track.duration}} minutes</p> 
        
        <!--delete track-->
        {% if tribe.user == user or user.is_superuser or track.track.user == user %}
            <form action="{% url 'deleteTrack' tribe.id playlist.id track.track.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete track</button>
            </form>
        {% endif %}
        
            <div class="d-flex">
            <!--lajk-->
            <form action="{% url 'upvote' tribe.id playlist.id track.track.id %}" method="post" role="form" >
                {% csrf_token %}
                {% if tribe.user == user or user in tribe.member.all %}
                    <button type="submit"><i class="fa fa-thumbs-up" aria-hidden="true"></i></button>
                {% else %}
                    <p type="submit"><i class="fa fa-thumbs-up" aria-hidden="true" disabled></i></p>
                {% endif %}
            </form>
            <span class="vote-score float-left">{{ track.track.upvote_score }}</span>
            <!--dislajk-->
            <form action="{% url 'downvote' tribe.id playlist.id track.track.id %}" method="post" role="form" >
                {% csrf_token %}
                {% if tribe.user == user or user in tribe.member.all %}
                    <button type="submit"><i class="fa fa-thumbs-down" aria-hidden="true"></i></button>
                {% else %}
                    <p type="submit"><i class="fa fa-thumbs-down" aria-hidden="true" disabled></i></p>
                {% endif %}
            </form>
            <span class="vote-score float-left">{{ track.track.downvote_score }}</span>
            </div>
        
            <!--komentari-->
            <div class="mb-4">
            {% if track.comments.count == 0 %}
                <span class = "show_hide" style="font-size:18px;"> Comment</span>
            {% else %}
                <span class = "show_hide" style="font-size:18px;"> Comments {{ track.comments.count }}</span>
            {% endif %}
            </div>
            <div class="comments_section container" style="display: none;">
                {% if track.comments %}
                {% for comment in track.comments %}
                    <div class="comment_container d-flex">
                        <img stle="width:25px; height:25px" src="{{ comment.image }}">
                        <div class="ml-2">
                        <p style="font-size:18px;">{{ comment.text }}</p>
                        <p style="font-size:18px;">Sent : {{ comment.created_at }}</p>
                        <p style="font-size:18px;">Author : {{ comment.user }} </p>
                        </div>
                        <!--izbriši komentar-->
                        {% if user.is_authenticated and tribe.user == user or user.is_superuser %}
                            <form action="{% url 'deleteComment' tribe.id playlist.id comment.id %}" method="post" class="ml-2">
                                {% csrf_token %}
                                <button type ="submit" class="btn btn-danger">Delete Comment </button>
                            </form>
                        {% endif %}
                    </div>
                {% endfor %}
                {% else %}
                    <p style="font-size:18px;">No one commented this track </p>
                {% endif %}
                <!--dodaj komentar-->
                {% if tribe.user == user or user in tribe.member.all %}
                <div class="comment_container mt-2">
                    <form role="form" action = "{% url 'comment' tribe.id playlist.id track.track.id  %}" method="post" >
                        {% csrf_token %}
                        <textarea style="font-size:18px;" type="text" name="text" maxlength="500" required placeholder="write comment..."></textarea> 
                        <button style="font-size:18px;" class="btn btn-success" type="submit">Comment</button>
                    </form>
                </div>
                {% endif %}
            </div>
        
        
    </div>
    {% endfor %}
    {% else %}
        <p style="text-align: center;">Lista je prazna</p>
    {% endif %}
    <!--funkcionalnost za prikaz i skrivanje komentara-->
    <script>
        $(document).ready(function(){
            $(".show_hide").click(function(){
                $(".comments_section").slideToggle();
            });

        });
    </script>
{% endblock %}